# Generated by Django 2.2.4 on 2019-08-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshniso', '0003_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
