# Generated by Django 2.2.4 on 2019-08-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshniso', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This a test description'),
            preserve_default=False,
        ),
    ]
