# Generated by Django 2.2.4 on 2019-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freshniso', '0005_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
